[package]
name = "askama_shared"
version = "0.8.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
description = "Shared code for Askama"
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT/Apache-2.0"
workspace = ".."
edition = "2018"

[features]
full = ["with-i18n", "serde_json", "serde_yaml"]
with-i18n = ["fluent-bundle", "lazy_static", "accept-language"]

[dependencies]
askama_escape = { version = "0.2.0", path = "../askama_escape" }
humansize = "1.1.0"
num-traits = "0.2.6"
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", optional = true }
serde_yaml = { version = "0.8", optional = true }
toml = "0.4"
fluent-bundle = { version = "0.5", optional = true }
lazy_static = { version = "1.2", optional = true }
accept-language = { version = "2.0", optional = true }
