[package]
name = "askama_parser"
version = "0.1.0"
description = "Askama template syntax parser"
homepage = "https://github.com/djc/askama"
repository = "https://github.com/djc/askama"
license = "MIT OR Apache-2.0"
workspace = ".."
readme = "../README.md"
edition = "2021"
rust-version = "1.58"

[dependencies]
nom = "7"
