name: Setup Rust Environment

inputs:
  os:
    default: ubuntu-latest
  rusthash:
    required: true
      
  
steps:
  - uses: actions/cache@v3
    with:
      path: |
        ~/.cargo/bin/
        ~/.cargo/registry/index/
        ~/.cargo/registry/cache/
        ~/.cargo/git/db/
        target/
      key: ${{ inputs.os }}-${{ inputs.rusthash }}-cargo-${{ hashFiles('**/Cargo.lock') }}
