name: Setup Rust Environment

inputs:
  os:
    description: Runner Type for generating hash-key
    default: ubuntu-latest
    required: false
  toolchain:
    description: Pass-through to toolchain on actions-rs
    default: stable
    required: false
  components:
    description: Pass-through to components on actions-rs
    required: false

runs:
  using: composite
  steps:
    - uses: actions-rs/toolchain@v1
      id: toolchain-install
      with:
        profile: minimal
        override: true
        toolchain: ${{ inputs.toolchain }}
        components: ${{ inputs.components }}  
    - uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ inputs.os }}-${{ steps.toolchain-install.outputs.rustc_hash }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}
