[package]
name = "random_code"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.58"
publish = false

[dependencies]
arbitrary = { version = "1.3.0", features = ["derive"] }

[[bin]]
name = "translate-dump"
test = false
doc = false
